# Generated by Django 6.0.1 on 2026-02-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_quizresult_results_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='content_type',
            field=models.CharField(default='MCQ', max_length=50),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
