# Generated by Django 6.0.1 on 2026-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_quizresult_content_type_quizresult_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
